# Generated by Django 4.2.5 on 2023-09-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('Car', 'Car'), ('Home', 'Home'), ('Edcation', 'Education'), ('Personal', 'Personal')], max_length=10)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('term_period', models.PositiveIntegerField()),
                ('disbursal_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit_score', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit'), ('L', 'Loan')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aadhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.registeration')),
                ('loan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.loanapplied')),
            ],
        ),
        migrations.AddField(
            model_name='loanapplied',
            name='aadhar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.registeration'),
        ),
        migrations.CreateModel(
            name='EMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.loanapplied')),
            ],
        ),
    ]
